title: jartigag.blog                  # The title of the blog
author: "@jartigag"                   # Your name
email: jartigag@pm.me                 # your email shown in the footer
url: https://jartigag.github.io/blog/ # this is your site's root address.
description: >                        # this means to ignore newlines until "show_excerpts:"
  reconnecting.. üåê
favicon: "./favicon.ico" # set the favicon of the site
timezone: Europe/Madrid #  The docs say it has to be the IANA term.

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title/
related: true       # set to true to show related posts at the end of a post
show-tags: true     # set to true to show tags at the end of a post

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
arreando:
  avatar_url: "/blog/assets/images/profile.png"        # avatar in about page
                                                       # header image is in /assets/css/header.jpg
  about_you: telecom engineer, musician for a lifetime # short description about you in about page
  date_format: "%b %d"                                 # date format of posts in home page
  back_to: "blog"                                      # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter:    jartigag
    github:     jartigag
    telegram:   jartigag
    mastodon: # Mastodon instances
    - username: jartigag
      instance: mastodon.social
    linkedin:   javier-artiga-garijo
    rss: RSS

# Build settings
remote_theme: jartigag/arreando # note, please use jartigag/arreando if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
